class DuplicateLeadError(Exception): ...
class LeadNotFoundError(Exception): ...
class FileValidationError(Exception): ...
class StorageError(Exception): ...
class InvalidCredentialsError(Exception): ...
class IllegalTransitionError(Exception): ...
